CREATE TABLE rate (
	rate FLOAT,
	time NUMBER
);
CREATE TABLE ACCOUNT (
	accountno NUMBER NOT NULL,
	type VARCHAR(50),
	CUSTOMERID NUMBER,
	BALANCE FLOAT,
	status NUMBER,
	PRIMARY KEY (accountno)
);
CREATE TABLE atm (
	atmID NUMBER NOT NULL,
	location VARCHAR(50),
	balance FLOAT,
	region VARCHAR(50),
	thresholdValue FLOAT,
	status NUMBER,
	PRIMARY KEY (atmID)
);
CREATE TABLE BILL (
	BIILID NUMBER NOT NULL,
	CUSTOMERID NUMBER,
	type VARCHAR(50),
	BILLAMOUNT FLOAT,
	dateField DATE,
	REFID NUMBER,
	PRIMARY KEY (BIILID)
);
CREATE TABLE branchAccount (
	accountNo  NUMBER NOT NULL,
	branchid NUMBER,
	thresholdValue FLOAT,
	balance FLOAT,
	status NUMBER,
	PRIMARY KEY (accountNo )
);
CREATE TABLE Branch (
	branchid NUMBER NOT NULL,
	location VARCHAR(50),
	region VARCHAR(50),
	accountno NUMBER,
	branchmanager NUMBER,
	status NUMBER,
	PRIMARY KEY (branchid)
);

CREATE TABLE CUSTOMER (
	customerID NUMBER NOT NULL,
	NAME VARCHAR(50),
	DOB VARCHAR(50),
	GENDER CHAR,
	ADDRESS VARCHAR(50),
	status NUMBER,
	ATMSTATUS VARCHAR(50),
	PRIMARY KEY (customerID)
);

CREATE TABLE employee (
	employeeid NUMBER NOT NULL,
	ENAME VARCHAR(50),
	EGENDER CHAR,
	EADDRESS VARCHAR(50),
	EDESIGNATION VARCHAR(50),
	ESTATUS NUMBER,
	DOB DATE,
	PRIMARY KEY (employeeid)
);
CREATE TABLE fixedaccount (
	accountno NUMBER NOT NULL,
	DEPOSITAMT FLOAT,
	years NUMBER,
	macturitybalance FLOAT,
	CURRENTDATE DATE,
	PRIMARY KEY (accountno)
);
CREATE TABLE LOGIN (
	USERNAME NUMBER NOT NULL,
	PASSWORD VARCHAR(50),
	SEQANS1 VARCHAR(50),
	SEQANS2 VARCHAR(50),
	PRIMARY KEY (USERNAME)
);
CREATE TABLE REQUEST (
	requestid NUMBER NOT NULL,
	accountno NUMBER,
	type VARCHAR(50),
	reqdate DATE,
	PRIMARY KEY (requestid)
);
CREATE TABLE TRANSACTION (
	transactionID NUMBER NOT NULL,
	accountno NUMBER,
	transactiondate DATE,
	type VARCHAR(50),
	amount FLOAT,
	PRIMARY KEY (transactionID)
);

CREATE SEQUENCE transactionid
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE requestid
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE accountno
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE employeeid
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE SEQ_CUSTOMERID
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE branchid
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE accountno
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE ATM_ID
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE BILLREFID
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE AccountNumber
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
INSERT INTO rate values(0.07,1);
INSERT INTO rate values(0.0725,3);
INSERT INTO rate values(0.075,5);

INSERT INTO LOGIN values(12345678,'test','abc','def');
